- name: Update apt packages
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install system dependencies
  apt:
    name:
      - python3-pip
      - python3-dev
      - libpq-dev
      - git
      - nginx
      - virtualenv
      - python3-venv
    state: present

- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Ensure the app directory exists
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: ubuntu
    group: www-data
    mode: '0755'

- name: Clone the Django app from GitHub
  git:
    repo: "https://github.com/Laban254/customer-management-api"
    dest: "{{ app_dir }}"
    force: yes

- name: Create virtual environment
  command: python3 -m venv {{ app_dir }}/venv
  args:
    creates: {{ app_dir }}/venv/bin/activate

- name: Install Python dependencies in the virtual environment
  pip:
    requirements: {{ app_dir }}/requirements.txt
    virtualenv: {{ app_dir }}/venv

- name: Configure Gunicorn
  copy:
    dest: /etc/systemd/system/gunicorn.service
    content: |
      [Unit]
      Description=gunicorn daemon for mydjangoapp
      After=network.target

      [Service]
      User=ubuntu
      Group=www-data
      WorkingDirectory={{ app_dir }}  
      ExecStart={{ app_dir }}/venv/bin/gunicorn --workers 3 --bind 0.0.0.0:8000 customer_orders_service.wsgi:application
      StandardOutput=journal
      StandardError=journal

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply changes
  command: systemctl daemon-reload

- name: Enable and start Gunicorn
  systemd:
    name: gunicorn
    enabled: true
    state: started

- name: Configure Nginx
  copy:
    dest: /etc/nginx/sites-available/mydjangoapp
    content: |
      server {
          listen 80;
          server_name 3.87.203.152;  

          location / {
              proxy_pass http://127.0.0.1:8000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }

          location /static/ {
              alias {{ app_dir }}/static/;
          }

          location /media/ {
              alias {{ app_dir }}/media/;
          }

          access_log /var/log/nginx/mydjangoapp_access.log;
          error_log /var/log/nginx/mydjangoapp_error.log;
      }

- name: Enable the Nginx configuration
  file:
    src: /etc/nginx/sites-available/mydjangoapp
    dest: /etc/nginx/sites-enabled/mydjangoapp
    state: link

- name: Restart Gunicorn
  systemd:
    name: gunicorn
    state: restarted

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
